import React from "react";
import SEO from "@/components/SEO";
import Navigation from "@/components/Navigation";

const AIDisclaimer = () => {
  return (
    <>
      <Navigation />
      <main className="container mx-auto px-4 py-10 mt-24">
      <SEO
        title="AI Disclaimer | Helpzz"
        description="Important information about Helpzz's AI features and limitations."
        canonicalPath="/ai-disclaimer"
      />
      <article className="max-w-3xl mx-auto space-y-6 prose prose-slate">
        <h1 className="text-4xl font-bold tracking-tight">Helpzz AI Disclaimer</h1>
        <p className="text-sm text-muted-foreground">(Last updated: October 2025)</p>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">1. General Disclaimer</h2>
          <p>
            Helpzz is an AI-powered platform operated by Lumatra Ltd (company no. SC813300),
            designed to assist businesses in automating customer support tasks such as FAQs and
            query handling.
          </p>
          <p>
            While we strive to ensure that Helpzz produces accurate and helpful responses, the
            content generated by our AI tools should not be considered professional advice or
            guaranteed factual information.
          </p>
          <p>
            You are responsible for reviewing, editing, and approving any AI-generated material
            before it is shared publicly or used in your business communications.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">2. No Warranties</h2>
          <p>
            Helpzz is provided on an "as is" and "as available" basis. Lumatra Ltd makes no
            warranties, express or implied, regarding:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>the accuracy, reliability, or completeness of AI-generated outputs;</li>
            <li>the suitability of Helpzz for any specific purpose; or</li>
            <li>uninterrupted or error-free operation of the platform.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">3. Limitation of Liability</h2>
          <p>To the fullest extent permitted by law:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              Lumatra Ltd shall not be liable for any losses, damages, or claims arising from
              reliance on AI-generated content;
            </li>
            <li>
              You acknowledge that AI tools can produce errors, omissions, or unintended outputs,
              and you use Helpzz at your own discretion and risk.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">4. Responsible Use</h2>
          <p>Users must ensure that AI-generated outputs are:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Reviewed and verified for accuracy and appropriateness before use;</li>
            <li>Compliant with all applicable laws and regulations; and</li>
            <li>Aligned with ethical and business standards.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">5. Contact</h2>
          <p>Lumatra Ltd (Company no. SC813300)</p>
          <p>132 Strathcarron Drive, Paisley, Scotland, PA2 7AY</p>
          <p>Email: info@lumatra.net</p>
        </section>
      </article>
    </main>
    </>
  );
};

export default AIDisclaimer;
