// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkkprgkwxyvlqurguxoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpra3ByZ2t3eHl2bHF1cmd1eG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDI2ODcsImV4cCI6MjA3NDExODY4N30.-ok3ijtJ6_Q-_3I-oHcP2x0n2yOdY6teRx7kF5s25mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});